option(OPERA_BUILD_BENCHMARKS "Build the benchmark" OFF)

if(OPERA_BUILD_BENCHMARKS)
  message(STATUS "Building the benchmark")
  add_subdirectory(tpch_q1)
  add_subdirectory(tpch_q4)
  add_subdirectory(tpch_q6)
  add_subdirectory(tpch_q12)
  add_subdirectory(tpch_q15)
  add_subdirectory(tpch_q17)
  add_subdirectory(tpch_q19)
endif()
